language: csharp
solution: NetworkTables.sln

os:
  - linux
  - osx

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      libstdc++6-4.7-dbg

install:
  - nuget restore NetworkTables.sln
  - nuget install NUnit.Console -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=CI NetworkTables.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./NetworkTables.Test/Output/NetworkTables.Test.dll -v
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./NetworkTablesCore.Test/Output/NetworkTablesCore.Test.dll -v
